apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alloy-alias
spec:
  type: ExternalName
  externalName: k8s-monitoring-alloy-singleton.monitoring.svc.cluster.local
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
