admin:
  existingSecret: grafana-admin-credentials
  userKey: admin-user
  passwordKey: admin-password

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: ALL
    folder: /var/lib/grafana/dashboards/default
  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "1"
    searchNamespace: ALL
