admin:
  existingSecret: grafana-admin-credentials
  userKey: admin-user
  passwordKey: admin-password

sidecar:
  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "1"
    searchNamespace: ALL
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: ALL
    folder: /tmp/dashboards
    folderAnnotation: grafana_folder
    provider:
      foldersFromFilesStructure: false

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'Default'
      orgId: 1
      folder: 'Default'
      type: file
      disableDeletion: true
      options:
        path: /tmp/dashboards/Default
    - name: 'K8s'
      orgId: 1
      folder: 'K8s'
      type: file
      disableDeletion: true
      options:
        path: /tmp/dashboards/k8s
    - name: 'Loki'
      orgId: 1
      folder: 'Loki'
      type: file
      disableDeletion: true
      options:
        path: /tmp/dashboards/loki-ssd
    - name: 'Tempo'
      orgId: 1
      folder: 'Tempo'
      type: file
      disableDeletion: true
      options:
        path: /tmp/dashboards/tempo

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  timeoutSeconds: 5
livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 120
  timeoutSeconds: 5
