spring:
  application:
    name: spring-boot-observability
management:
  endpoints:
    web:
      exposure:
        # Expose prometheus for metrics, otlp is still used for logs/traces
        include: "health,prometheus"
  # This isn't necessary because the default is already true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        # Essential for P99 latencies in Grafana
        http.server.requests: true
  tracing:
    sampling:
      # Ensure every request is sampled
      probability: 1.0
  observations:
    key-values:
      application: spring-boot-observability
  otlp:
    tracing:
      endpoint: http://localhost:4317

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#    include-application-name: false