server:
  # Enable Alloy to push metrics via remote_write
  remoteWriteReceiver: true
  
  extraFlags:
    - web.enable-remote-write-receiver
    - web.enable-lifecycle
  
  persistentVolume:
    enabled: true
    size: 20Gi # Local disk storage for lean setup

# Enable/Disable components for a simple setup
alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
prometheus-node-exporter:
  enabled: true
  # DOCKER-DESKTOP: Disabled hostRootfs mount because Docker Desktop 
  # does not support 'shared' mount propagation for the root path.
  # FOR PRODUCTION: Set to 'true' to allow monitoring of host disk usage.
  hostRootFsMount:
    enabled: false
kube-state-metrics:
  enabled: true