datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-server.monitoring.svc
        isDefault: true
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
            - datasourceUid: 'tempo'
              name: 'trace_id'

      - name: Loki
        type: loki
        uid: loki
        url: http://loki.monitoring.svc:3100
        jsonData:
          derivedFields:
            - datasourceUid: 'tempo'
              name: 'TraceID'
              matcherRegex: '\[.+?,(\w+),(\w+)?\]'
              url: '$${__value.raw}'
              urlDisplayLabel: 'View Trace'

      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo.monitoring.svc:3200
        jsonData:
          # Trace to Logs
          tracesToLogs:
            datasourceUid: 'loki'
            tags: ['job', 'instance', 'pod', 'namespace']
            mappedTags:
              - key: 'service.name'
                value: 'service_name'
            filterByTraceId: true
            filterBySpanId: false
          
          # Trace to Metrics (Service Map)
          tracesToMetrics:
            datasourceUid: 'prometheus'
            spanAttributes:
              - key: 'service.name'
                value: 'service_name'
          
          serviceMap:
            datasourceUid: 'prometheus'
          nodeGraph:
            enabled: true

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: ALL
    # Folder to store the dashboards in Grafana
    folder: /var/lib/grafana/dashboards/default