architecture: replicaset
replicaCount: 2
replicaSetName: mgrs
auth:
  rootUser: admin
  rootPassword: password
arbiter:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
global:
  resourcesPreset: "none"
persistence:
  enabled: false
image:
  tag: latest
