server:
  # Enable Alloy to push metrics via remote_write
  remoteWriteReceiver: true
  
  extraFlags:
    - web.enable-remote-write-receiver
    - web.enable-lifecycle
  
  persistentVolume:
    enabled: true
    size: 20Gi # Local disk storage for lean setup

# Disable components we don't need for a simple setup
alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
prometheus-node-exporter:
  enabled: false