tempo:
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 10
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 10

  extraArgs:
    mem-ballast-size-mbs: 16

# Manually define the config to ensure correct S3 field names
config: |
  server:
    http_listen_port: 3200
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal
  distributor:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
  metrics_generator:
    storage:
      path: /var/tempo/wal
      remote_write:
        - url: http://prometheus-server.monitoring.svc/api/v1/write
    traces_storage:
      path: /var/tempo/traces
  overrides:
    metrics_generator_processors: [service-graphs, span-metrics, local-blocks]

persistence:
  enabled: true
  size: 10Gi

